image: alpine/latest
packages:
- rust
- rust-clippy
sources:
- https://git.sr.ht/~loshz/chargectl
environment:
  repo: chargectl
tasks:
- lint: |
    cd $repo
    cargo fmt -- --check
    cargo clippy --tests -- --no-deps -D warnings
- test: |
    cd $repo
    cargo test --no-fail-fast --all-features
