name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Lint code and run tests.
      - run: |
          cargo fmt -- --check
          cargo clippy --tests -- --no-deps -D warnings

      # Run all tests.
      - run: cargo test --no-fail-fast --all-features
